### PR TITLE
Fix Rubycritic's Analysers running twice on the first run

### LINKED ISSUE #94: Analysers running twice in some cases
Haven't been able to dig into this yet, but it's been happening a lot lately. Will report more as it comes up. Figured I'd post in case others were experiencing this. Seems to happen whenever I destroy the tmp folder:

```
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ rm -rf tmp
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ bin/rubycritic lib
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
New critique at file:///Users/Bodah/repos/rubycritic/tmp/rubycritic/overview.html
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ vim lib/rubycritic/analysers
analysers/           analysers_runner.rb
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ vim lib/rubycritic/analysers_runner.rb
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ rm -rf tmp
Bodah@jbodah-local 2.1.3p242 ~/repos/rubycritic (master) $ bin/rubycritic lib

[22, 31] in /Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb
   22:       @paths = paths
   23:     end
   24:
   25:     def run
   26:       require 'rubygems'; require 'byebug'; byebug
=> 27:       ANALYSERS.each do |analyser_class|
   28:         analyser_instance = analyser_class.new(analysed_modules)
   29:         puts "running #{analyser_instance}"
   30:         analyser_instance.run
   31:       end
(byebug) require 'ap'
true
(byebug) ap caller
[
    [ 0] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `eval'",
    [ 1] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `safe_eval'",
    [ 2] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:53:in `warning_eval'",
    [ 3] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `block in multiple_thread_eval'",
    [ 4] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:92:in `allowing_other_threads'",
    [ 5] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `multiple_thread_eval'",
    [ 6] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:164:in `block in run_cmd'",
    [ 7] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:169:in `safely'",
    [ 8] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:160:in `run_cmd'",
    [ 9] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:149:in `repl'",
    [10] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:98:in `process_commands'",
    [11] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:56:in `at_line'",
    [12] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/context.rb:96:in `at_line'",
    [13] "/Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb:27:in `run'",
    [14] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:19:in `critique'",
    [15] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:15:in `execute'",
    [16] "/Users/Bodah/repos/rubycritic/lib/rubycritic/cli/application.rb:17:in `execute'",
    [17] "bin/rubycritic:9:in `<main>'"
]
nil
(byebug) c
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................

[22, 31] in /Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb
   22:       @paths = paths
   23:     end
   24:
   25:     def run
   26:       ANALYSERS.each do |analyser_class|
=> 27:         analyser_instance = analyser_class.new(analysed_modules)
   28:         puts "running #{analyser_instance}"
   29:         analyser_instance.run
   30:       end
   31:       analysed_modules
(byebug) ap caller
[
    [ 0] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `eval'",
    [ 1] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:59:in `safe_eval'",
    [ 2] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:53:in `warning_eval'",
    [ 3] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `block in multiple_thread_eval'",
    [ 4] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:92:in `allowing_other_threads'",
    [ 5] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/helpers/eval.rb:29:in `multiple_thread_eval'",
    [ 6] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:164:in `block in run_cmd'",
    [ 7] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:169:in `safely'",
    [ 8] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:160:in `run_cmd'",
    [ 9] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:149:in `repl'",
    [10] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:98:in `process_commands'",
    [11] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/processors/command_processor.rb:56:in `at_line'",
    [12] "/Users/Bodah/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/byebug-8.2.1/lib/byebug/context.rb:96:in `at_line'",
    [13] "/Users/Bodah/repos/rubycritic/lib/rubycritic/analysers_runner.rb:27:in `run'",
    [14] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:35:in `block in analysed_modules_before'",
    [15] "/Users/Bodah/repos/rubycritic/lib/rubycritic/source_control_systems/git.rb:33:in `travel_to_head'",
    [16] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:34:in `analysed_modules_before'",
    [17] "/Users/Bodah/repos/rubycritic/lib/rubycritic/revision_comparator.rb:19:in `set_statuses'",
    [18] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:20:in `critique'",
    [19] "/Users/Bodah/repos/rubycritic/lib/rubycritic/commands/default.rb:15:in `execute'",
    [20] "/Users/Bodah/repos/rubycritic/lib/rubycritic/cli/application.rb:17:in `execute'",
    [21] "bin/rubycritic:9:in `<main>'"
]
nil
(byebug) c
running flay smells

running flog smells
..................................................
running reek smells
..................................................
running complexity
..................................................
running attributes
..................................................
running churn
..................................................
New critique at file:///Users/Bodah/repos/rubycritic/tmp/rubycritic/overview.html
```

### PR DESCRIPTION
**Pull request by Onumis**
Fix #94 

This changes `RevisionComparator` so that it does not attempt any comparison if there is nothing to compare to!

### CODE REVIEW

File: test/test_helper.rb [hunk 1]
```diff
@@ -1,6 +1,6 @@
 require 'minitest/autorun'
 require 'minitest/pride'
-require 'mocha/setup'
+require 'mocha/mini_test'
```
Comment (Onumis) [inline test/test_helper.rb]: `require 'mocha/setup'` is from mocha < v1.0

File: test/lib/rubycritic/revision_comparator_test.rb [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+                          .returns(stub(revision?: true))
+      end
+
+      context 'without previously cached results' do
+        before do
+          subject.expects(:revision_file).returns('foo')
+          File.expects(:file?).with('foo').returns(false)
+        end
+
+        it 'attempts to load previously cached results' do
```
Comment (troessner) [inline test/lib/rubycritic/revision_comparator_test.rb]: Wait, is that  a typo? The context says "without cached results"?

**Comment by troessner** [comment]
One comment, then lgtm ;)

File: test/lib/rubycritic/revision_comparator_test.rb (hunk 2 above)
Comment (Onumis) [inline test/lib/rubycritic/revision_comparator_test.rb]: Yeah, probably just need to test that it does not invoke SmellsStatusSetter.

I'll fix it once I get back to my pc

Comment (troessner) [inline test/lib/rubycritic/revision_comparator_test.rb]: Sorry for not being clear here: My problem with those tests are that this context says:

>> 'without previously cached results'

and the example says:

>> 'attempts to load previously cached results'

From a logical point of view this doesn't seem to make sense. If there are no cached results it shouldn't try to load them.
Apart from that below is a context that says:

>> 'with previously cached results'

but has the **exact** same example:

>> 'attempts to load previously cached results'

So I'm not sure what's going on here, but if I just read the specs as an innocent reader this is very confusing to me.

Comment (Onumis) [inline test/lib/rubycritic/revision_comparator_test.rb]: Of course! I've made a few changes, should be better now.

**Comment by Onumis** [comment]
Updated!

**Comment by troessner** [comment]
Adding specs and at the same time removing application code - I like this one a lot!
Merged ;)

**Comment by troessner** [comment]
Actually this also warrants a bugfix release I believe.
Would you like to have the honours @Onumis ? ;)

**Comment by Onumis** [comment]
Yep, will do :)
